name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
#-----------------------------------------------N0M0A0P D0O0W0N0L0O0A0D and I0N0S0T0A0L0L
    - name: N0M0A0P D0O0W0N0L0O0A0D and I0N0S0T0A0L0L
      run:  .\N0M0A0P.ps1 
      shell: powershell 
      
    - name: goto
      run:  cd "C:\Tools"
    - name: RUN
      run: Invoke-Expression -Command "C:\tools\Nmap\nmap.exe"
      
#-----------------------------------------------M0S0F D0O0W0N0L0O0A0D and I0N0S0T0A0L0L
    - name: M0S0F D0O0W0N0L0O0A0D
      run: F.\M0S0F-D0O0W0N0L0O0A0D.ps1
      shell: powershell
#---------------------------------------------- N0J0R0O0K
    - name: N0J0R0O0K D0O0W0N0L0O0A0D
      run:  Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: N0J0R0O0K Extract
      run: Expand-Archive ngrok.zip
    - name: N0J0R0O0K Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 338
